name: Twitter Sentiment Analysis

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  job_var:
    env:
      ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
      ACCESS_SECRET: ${{ secrets.ACCESS_SECRET }}
      CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
      CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - if: ${{ secrets.ACCESS_KEY != '' }}
      run: echo 'This step will only run if ACCESS_KEY has a value set.'
    - if: ${{ secrets.ACCESS_KEY == '' }}
      run: echo 'This step will only run if ACCESS_KEY does not have a value set.'
    - shell: python
      run: |
        import os
        print(sorted(os.environ))
        KEYS = "ACCESS_KEY ACCESS_SECRET CONSUMER_KEY CONSUMER_SECRET".split()
        for key in KEYS:
            print(f"{key} in os.environ: {key in os.environ}")
            print(f"os.environ[{key}] is truthy: {bool(os.environ[key])}")

  step_var:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - env:
         ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
      if: ${{ secrets.ACCESS_KEY != '' }}
      run: echo 'This step will only run if ACCESS_KEY has a value set.'
    - env:
         ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
      if: ${{ secrets.ACCESS_KEY == '' }}
      run: echo 'This step will only run if ACCESS_KEY does not have a value set.'
    - env:
        ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
        ACCESS_SECRET: ${{ secrets.ACCESS_SECRET }}
        CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
        CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
      shell: python
      run: |
        import os
        print(sorted(os.environ))
        KEYS = "ACCESS_KEY ACCESS_SECRET CONSUMER_KEY CONSUMER_SECRET".split()
        for key in KEYS:
            print(f"{key} in os.environ: {key in os.environ}")
            print(f"os.environ[{key}] is truthy: {bool(os.environ[key])}")
  
  sentiment_analysis:
    runs-on: ubuntu-latest
    env:
      ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
      ACCESS_SECRET: ${{ secrets.ACCESS_SECRET }}
      CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
      CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - env:
        ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
      shell: python
      run: "import os ; print(list(os.environ)) ; assert os.getenv('ACCESS_KEY')"

    - name: Setup Python environment
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run tweet extraction process
      run: |
        python add_tweets_1.py
        python add_sentiment_to_tweets_2.py

    - name: Run recommendation method
      run: |
        python recommender_function_6.py

    - name: Commit and push changes
      uses: EndBug/add-and-commit@v7
      with:
        author_name: rohan472000
        author_email: anand00rohan@example.com
        message: Updated sentiment analysis data
        add: 'updated_reftweets.csv'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
